### ISSUE TITLE
Imports fail in 0.8.1

### ISSUE THREAD

**Issue by thusoy** [kvesteri/wtforms-components#9]
My tests started failing on 0.8.1, with the following traceback:

```
from wtforms_alchemy import model_form_factory
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/wtforms_alchemy/__init__.py", line 5, in <module>
    from wtforms_components import (
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/wtforms_components/__init__.py", line 2, in <module>
    from .fields import (
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/wtforms_components/fields/__init__.py", line 2, in <module>
    from .html5 import (
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/wtforms_components/fields/html5.py", line 3, in <module>
    from ..widgets import (
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/wtforms_components/widgets.py", line 11, in <module>
    from .validators import DateRange, TimeRange
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/wtforms_components/validators.py", line 5, in <module>
    from validators import is_email as email
ImportError: cannot import name is_email
```

Works fine with wtforms-components 0.8.0.

**Comment by prokoptsev** [comment]
Same problem.
Libs version:
```
WTForms-Alchemy==0.13.1
WTForms-Components==0.9.8
validators==0.9
```
